services:
  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scraper
    #ports:
    #  - "8000:8000"
    networks:
      - npm-net
    env_file:
      - .env

networks:
  npm-net:
    name: npm-net
    external: true
